# Generated by Django 2.2.16 on 2022-06-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220621_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(default=508409, verbose_name='Код подтверждения'),
        ),
    ]
