# Generated by Django 2.2.16 on 2022-06-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220621_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(default=662730, verbose_name='Код подтверждения'),
        ),
    ]
