# Generated by Django 2.2.16 on 2022-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220621_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(default=296172, verbose_name='Код подтверждения'),
        ),
    ]
